services:
#  redis:
#    image: 'bitnami/redis:latest'
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    ports:
#      - '6579:6379'
#  etcd:
#    image: 'bitnami/etcd:latest'
#    environment:
#      - ALLOW_NONE_AUTHENTICATION=yes
#      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2369
#    ports:
#      #      客户端通信接口
#      - 12369:2369
#      #      集群节点通信端口
#      - 12370:2570
#  etcdkeeper:
#      image: 'evildecay/etcdkeeper:latest'
#      container_name: "etcdkeeper"
#      environment:
#           HOST: "0.0.0.0"
#      ports:
#        - 12000:8080
#      depends_on:
#        - etcd
  grafana:
    image: grafana/grafana-enterprise:10.2.0
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      #      - 将本地的 prometheus 文件映射到容器内的配置文件
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      #      - 访问数据的端口
      - 9990:9090