---
--- Generated by Luanalysis
--- Created by xuhaidong.
--- DateTime: 2023/10/22 16:13
---

-- taskKey: deviceType:deviceID
local biz = KEYS[1]
local taskKey = redis.call('SRANDMEMBER', biz)
if not taskKey then
    redis.call('DEL', biz)
    return {"","","nomessage"}
end
local idList = redis.call('LRANGE', taskKey,0,-1)
redis.call('DEL', taskKey)
redis.call('SREM', biz, taskKey)
local _, deviceType = string.match(taskKey, "([^:]+):(.+)")
return {deviceType,idList,"ok"}
