---
--- Generated by Luanalysis
--- Created by xuhaidong.
--- DateTime: 2023/10/22 16:13
---

while true do
    local taskKey = redis.call('SRANDMEMBER', KEYS[1])
    if not taskKey then
        redis.call('DEL', KEYS[1])
        return {"","","nomessage"}
    end
    local deviceID = redis.call('RPOP', taskKey)
    if not deviceID then
        redis.call('SREM', KEYS[1], taskKey)
    else
        local _, deviceType = string.match(taskKey, "([^:]+):(.+)")
        return {deviceType,deviceID,"ok"}
    end
end
